export const SPOT_HOLD_DURATION_MINUTES = 15
export const CREATIVE_TOKEN_LENGTH = 32

export const SPOT_TYPE_COLORS = {
  PREMIUM: { bg: "bg-primary/10", border: "border-primary", text: "text-primary" },
  LARGE: { bg: "bg-stone-bg/50", border: "border-border", text: "text-foreground" },
  STANDARD: { bg: "bg-stone-bg/30", border: "border-border", text: "text-muted-foreground" },
  SMALL: { bg: "bg-stone-bg/20", border: "border-border", text: "text-muted-foreground" },
} as const

export const SPOT_STATUS_COLORS = {
  OPEN: { bg: "bg-primary/5", border: "border-primary", text: "text-primary" },
  HELD: { bg: "bg-amber-500/5", border: "border-amber-500 border-dashed", text: "text-amber-700" },
  SOLD: { bg: "bg-stone-bg/50 opacity-30", border: "border-border border-dashed", text: "text-muted-foreground" },
  UNAVAILABLE: { bg: "bg-stone-bg/20 opacity-30", border: "border-border border-dashed", text: "text-muted-foreground" },
} as const

export const CAMPAIGN_STATUS_LABELS: Record<string, string> = {
  DRAFT: "Draft",
  ACTIVE: "Active",
  SOLD_OUT: "Sold Out",
  CLOSED: "Closed",
  DESIGNING: "Designing",
  READY_FOR_PRINT: "Ready for Print",
  PRINTING: "Printing",
  MAILED: "Mailed",
  CANCELLED: "Cancelled",
}

export const GENERAL_SERVICES = [
  "Custom Consulting",
  "Free Estimates",
  "Delivery Services",
  "Installation Services",
  "Maintenance Plans",
  "Emergency Support",
  "Custom Orders",
]

export const PREPOPULATED_SERVICES: Record<string, string[]> = {
  plumbing: [
    "Plumbing Repairs",
    "Drain Cleaning",
    "Water Heaters",
    "Leak Detection",
    "Sewer Line Repair",
    "Fixture Installation",
    "Emergency Services",
  ],
  hvac: [
    "AC Installation",
    "AC Repair",
    "Heating Repair",
    "Furnace Installation",
    "Duct Cleaning",
    "Thermostat Installation",
    "Maintenance Services",
  ],
  electricians: [
    "Electrical Repairs",
    "Wiring & Rewiring",
    "Panel Upgrades",
    "Lighting Installation",
    "Outlet Installation",
    "Ceiling Fan Installation",
    "Safety Inspections",
  ],
  "water-damage-restoration": [
    "Water Extraction",
    "Dehumidification",
    "Mold Remediation",
    "Sewage Cleanup",
    "Structural Drying",
    "Content Restoration",
    "Flood Cleanup",
  ],
  roofing: [
    "Roof Repair",
    "Roof Replacement",
    "Shingle Installation",
    "Commercial Roofing",
    "Roof Inspection",
    "Gutter Installation",
    "Storm Damage Repair",
  ],
  "pest-control": [
    "Termite Treatment",
    "Rodent Control",
    "Insect Extermination",
    "Mosquito Control",
    "Bed Bug Treatment",
    "Wildlife Removal",
    "Preventative Maintenance",
  ],
  landscaping: [
    "Lawn Mowing",
    "Sod Installation",
    "Mulching & Weeding",
    "Sprinkler Repair",
    "Garden Design",
    "Hardscaping",
    "Yard Cleanups",
  ],
  cleaning: [
    "Residential Cleaning",
    "Commercial Cleaning",
    "Deep Cleaning",
    "Move-In/Move-Out Cleaning",
    "Window Washing",
    "Carpet Cleaning",
    "Janitorial Services",
  ],
  dentists: [
    "Teeth Cleaning",
    "Dental Fillings",
    "Root Canals",
    "Teeth Whitening",
    "Dental Crowns",
    "Emergency Dentistry",
    "Pediatric Dentistry",
  ],
  chiropractors: [
    "Spinal Adjustment",
    "Massage Therapy",
    "Physical Rehabilitation",
    "Sports Injury Treatment",
    "Nutritional Counseling",
    "Posture Correction",
    "Pain Management",
  ],
  "auto-repair": [
    "Oil Change",
    "Brake Repair",
    "Engine Diagnostics",
    "Tire Rotation",
    "Transmission Service",
    "AC & Heating Repair",
    "Suspension & Steering",
  ],
  "tree-services": [
    "Tree Trimming",
    "Tree Removal",
    "Stump Grinding",
    "Emergency Storm Cleanup",
    "Arborist Consultation",
    "Tree Planting",
    "Disease & Pest Treatment",
  ],
  painters: [
    "Interior Painting",
    "Exterior Painting",
    "Cabinet Refinishing",
    "Drywall Repair",
    "Wallpaper Removal",
    "Deck & Fence Staining",
    "Pressure Washing",
  ],
  handyman: [
    "General Repairs",
    "Drywall Patching",
    "Furniture Assembly",
    "Door & Window Repair",
    "TV Wall Mounting",
    "Minor Plumbing",
    "Minor Electrical",
  ],
  locksmiths: [
    "Emergency Lockouts",
    "Lock Rekeying",
    "Smart Lock Installation",
    "Key Duplication",
    "Deadbolt Installation",
    "Car Key Programming",
    "Commercial Security Systems",
  ],
  solar: [
    "Solar Panel Installation",
    "Solar Battery Backup",
    "System Maintenance & Repair",
    "Solar Inverter Replacement",
    "Energy Audits",
    "Commercial Solar Systems",
    "Solar Panel Cleaning",
  ],
  "pool-service": [
    "Weekly Pool Cleaning",
    "Chemical Balancing",
    "Pool Pump Repair",
    "Filter Cleaning & Repair",
    "Pool Leak Detection",
    "Equipment Automation",
    "Pool Opening & Closing",
  ],
  "junk-removal": [
    "Residential Cleanouts",
    "Appliance Disposal",
    "Furniture Removal",
    "Yard Waste Removal",
    "Construction Debris Hauling",
    "Commercial Junk Removal",
    "Donation Pickups",
  ],
  "security-systems": [
    "Smart Home Security",
    "CCTV Camera Installation",
    "Alarm System Monitoring",
    "Access Control Systems",
    "Video Doorbell Setup",
    "Commercial Security Solutions",
    "Intercom System Installation",
  ],
  "gyms-fitness": [
    "Personal Training",
    "Group Fitness Classes",
    "Cardio & Strength Equipment",
    "Yoga & Pilates Sessions",
    "Nutritional Coaching",
    "Locker Room & Sauna Amenities",
    "Youth Fitness Programs",
  ],
  "hair-salons-barbers": [
    "Haircuts & Styling",
    "Hair Coloring & Highlights",
    "Beard Trimming & Shaves",
    "Blowouts & Updos",
    "Hair Treatments (Keratin/Conditioning)",
    "Children's Haircuts",
    "Bridal & Event Hair Styling",
  ],
  "spas-massage": [
    "Swedish Massage",
    "Deep Tissue Massage",
    "Custom Facials",
    "Body Scrubs & Wraps",
    "Waxing & Hair Removal",
    "Hot Stone Therapy",
    "Aromatherapy Sessions",
  ],
  "restaurants-cafes": [
    "Dine-in Service",
    "Takeout & Delivery",
    "Catering Services",
    "Private Event Booking",
    "Specialty Coffee & Beverages",
    "Weekend Brunch",
    "Outdoor Patio Dining",
  ],
  "pet-grooming-boarding": [
    "Dog & Cat Grooming",
    "Pet Boarding / Lodging",
    "Doggie Daycare",
    "Nail Trimming & Ear Cleaning",
    "De-shedding Treatments",
    "Pet Taxi / Transportation",
    "Flea & Tick Baths",
  ],
  "real-estate": [
    "Home Buyer Representation",
    "Home Seller Listing Services",
    "Comparative Market Analysis",
    "Commercial Real Estate",
    "Property Management",
    "Real Estate Consulting",
    "Rental Property Finder",
  ],
  "tax-accounting": [
    "Tax Preparation & Filing",
    "Bookkeeping Services",
    "Payroll Processing",
    "IRS Audit Representation",
    "Small Business Consulting",
    "Financial Planning",
    "CPA Consultations",
  ],
  "legal-services": [
    "Family Law & Divorce",
    "Personal Injury Claims",
    "Estate Planning & Wills",
    "Business Law & Contracts",
    "Criminal Defense",
    "Real Estate Closings",
    "Bankruptcy Consultation",
  ],
  "dry-cleaning-laundry": [
    "Eco-Friendly Dry Cleaning",
    "Wash & Fold Laundry",
    "Alterations & Tailoring",
    "Wedding Gown Preservation",
    "Leather & Suede Cleaning",
    "Comforter & Linen Service",
    "Pickup & Delivery Services",
  ],
  "daycare-childcare": [
    "Infant & Toddler Care",
    "Preschool Curriculum",
    "After-School Programs",
    "Summer Camp Activities",
    "Nutritious Meals Provided",
    "Outdoor Play Areas",
    "Parent Communication App Updates",
  ],
  "car-wash-detailing": [
    "Exterior Car Wash",
    "Interior Vacuum & Dusting",
    "Hand Wax & Polish",
    "Ceramic Coating",
    "Upholstery & Carpet Steam Cleaning",
    "Headlight Restoration",
    "Mobile Detailing Services",
  ],
  "appliance-repair": [
    "Refrigerator Repair",
    "Washer & Dryer Service",
    "Oven & Stove Repair",
    "Dishwasher Repair",
    "Microwave Service",
    "Garbage Disposal Repair",
    "Emergency Appliance Diagnostic",
  ],
}
