export const SPOT_HOLD_DURATION_MINUTES = 15
export const CREATIVE_TOKEN_LENGTH = 32

export const SPOT_TYPE_COLORS = {
  PREMIUM: { bg: "bg-primary/10", border: "border-primary", text: "text-primary" },
  LARGE: { bg: "bg-stone-bg/50", border: "border-border", text: "text-foreground" },
  STANDARD: { bg: "bg-stone-bg/30", border: "border-border", text: "text-muted-foreground" },
  SMALL: { bg: "bg-stone-bg/20", border: "border-border", text: "text-muted-foreground" },
} as const

export const SPOT_STATUS_COLORS = {
  OPEN: { bg: "bg-primary/5", border: "border-primary", text: "text-primary" },
  HELD: { bg: "bg-amber-500/5", border: "border-amber-500 border-dashed", text: "text-amber-700" },
  SOLD: { bg: "bg-stone-bg/50 opacity-30", border: "border-border border-dashed", text: "text-muted-foreground" },
  UNAVAILABLE: { bg: "bg-stone-bg/20 opacity-30", border: "border-border border-dashed", text: "text-muted-foreground" },
} as const

export const CAMPAIGN_STATUS_LABELS: Record<string, string> = {
  DRAFT: "Draft",
  ACTIVE: "Active",
  SOLD_OUT: "Sold Out",
  CLOSED: "Closed",
  DESIGNING: "Designing",
  READY_FOR_PRINT: "Ready for Print",
  PRINTING: "Printing",
  MAILED: "Mailed",
  CANCELLED: "Cancelled",
}

export const GENERAL_SERVICES = [
  "Custom Consulting",
  "Free Estimates",
  "Delivery Services",
  "Installation Services",
  "Maintenance Plans",
  "Emergency Support",
  "Custom Orders",
]

export const PREPOPULATED_SERVICES: Record<string, string[]> = {
  plumbing: [
    "Plumbing Repairs",
    "Drain Cleaning",
    "Water Heaters",
    "Leak Detection",
    "Sewer Line Repair",
    "Fixture Installation",
    "Emergency Services",
  ],
  hvac: [
    "AC Installation",
    "AC Repair",
    "Heating Repair",
    "Furnace Installation",
    "Duct Cleaning",
    "Thermostat Installation",
    "Maintenance Services",
  ],
  electricians: [
    "Electrical Repairs",
    "Wiring & Rewiring",
    "Panel Upgrades",
    "Lighting Installation",
    "Outlet Installation",
    "Ceiling Fan Installation",
    "Safety Inspections",
  ],
  "water-damage-restoration": [
    "Water Extraction",
    "Dehumidification",
    "Mold Remediation",
    "Sewage Cleanup",
    "Structural Drying",
    "Content Restoration",
    "Flood Cleanup",
  ],
  roofing: [
    "Roof Repair",
    "Roof Replacement",
    "Shingle Installation",
    "Commercial Roofing",
    "Roof Inspection",
    "Gutter Installation",
    "Storm Damage Repair",
  ],
  "pest-control": [
    "Termite Treatment",
    "Rodent Control",
    "Insect Extermination",
    "Mosquito Control",
    "Bed Bug Treatment",
    "Wildlife Removal",
    "Preventative Maintenance",
  ],
  landscaping: [
    "Lawn Mowing",
    "Sod Installation",
    "Mulching & Weeding",
    "Sprinkler Repair",
    "Garden Design",
    "Hardscaping",
    "Yard Cleanups",
  ],
  cleaning: [
    "Residential Cleaning",
    "Commercial Cleaning",
    "Deep Cleaning",
    "Move-In/Move-Out Cleaning",
    "Window Washing",
    "Carpet Cleaning",
    "Janitorial Services",
  ],
  dentists: [
    "Teeth Cleaning",
    "Dental Fillings",
    "Root Canals",
    "Teeth Whitening",
    "Dental Crowns",
    "Emergency Dentistry",
    "Pediatric Dentistry",
  ],
  chiropractors: [
    "Spinal Adjustment",
    "Massage Therapy",
    "Physical Rehabilitation",
    "Sports Injury Treatment",
    "Nutritional Counseling",
    "Posture Correction",
    "Pain Management",
  ],
  "auto-repair": [
    "Oil Change",
    "Brake Repair",
    "Engine Diagnostics",
    "Tire Rotation",
    "Transmission Service",
    "AC & Heating Repair",
    "Suspension & Steering",
  ],
  "tree-services": [
    "Tree Trimming",
    "Tree Removal",
    "Stump Grinding",
    "Emergency Storm Cleanup",
    "Arborist Consultation",
    "Tree Planting",
    "Disease & Pest Treatment",
  ],
  painters: [
    "Interior Painting",
    "Exterior Painting",
    "Cabinet Refinishing",
    "Drywall Repair",
    "Wallpaper Removal",
    "Deck & Fence Staining",
    "Pressure Washing",
  ],
}
