export const TEMPLATE_1_ID = "nearhere-shared-card-9x12" as const

export const TEMPLATE_1_PRICING = {
  frontStandard: 490,
  backStandard: 590,
  frontDouble: 890,
  backDouble: 990,
  premiumCenterBack: 1490,
} as const

export type Template1SlotType = keyof typeof TEMPLATE_1_PRICING

export type AdvertiserSlot = {
  id: string
  templateId: typeof TEMPLATE_1_ID
  side: "front" | "back"
  positionId: string
  slotType: Template1SlotType
  category: string
  businessName: string
  description: string
  offer: string
  offerSubtext?: string
  phone: string
  websiteUrl: string
  displayWebsite: string
  qrCodeUrl: string
  qrLabel: string
  redemptionNote: string
  accentColor?: string
  iconType?: string
  logoUrl?: string
  price: number
}

const createSlot = (
  slot: Omit<AdvertiserSlot, "templateId" | "price">
): AdvertiserSlot => ({
  ...slot,
  templateId: TEMPLATE_1_ID,
  price: TEMPLATE_1_PRICING[slot.slotType],
})

export const template1FrontSlots: AdvertiserSlot[] = [
  createSlot({
    id: "template1-front-l1",
    side: "front",
    positionId: "F-L1",
    slotType: "frontStandard",
    category: "PLUMBING",
    businessName: "RIVER CITY PLUMBING",
    description: "Fast repairs, drain clearing, and water heater service from trusted local plumbers.",
    offer: "$50 OFF",
    offerSubtext: "Any service call",
    phone: "(210) 555-1001",
    websiteUrl: "https://rivercityplumbingtx.com",
    displayWebsite: "rivercityplumbingtx.com",
    qrCodeUrl: "/q/river-city-plumbing",
    qrLabel: "Scan offer",
    redemptionNote: "Mention this card.",
    accentColor: "#0B2F4A",
    iconType: "PL",
  }),
  createSlot({
    id: "template1-front-l2",
    side: "front",
    positionId: "F-L2",
    slotType: "frontStandard",
    category: "ELECTRICAL",
    businessName: "BRIGHT WAY ELECTRIC",
    description: "Licensed residential electrical repairs, panel upgrades, lighting, and safety checks.",
    offer: "$50 OFF",
    offerSubtext: "First completed repair",
    phone: "(210) 555-1005",
    websiteUrl: "https://brightwayelectric.com",
    displayWebsite: "brightwayelectric.com",
    qrCodeUrl: "/q/bright-way-electric",
    qrLabel: "Scan details",
    redemptionNote: "Mention this card.",
    accentColor: "#D13F1F",
    iconType: "EL",
  }),
  createSlot({
    id: "template1-front-l3",
    side: "front",
    positionId: "F-L3",
    slotType: "frontStandard",
    category: "GARAGE DOORS",
    businessName: "LONE STAR GARAGE DOORS",
    description: "Same-day spring repairs, quiet openers, tune-ups, and new garage door installation.",
    offer: "$40 OFF",
    offerSubtext: "Any garage door repair",
    phone: "(210) 555-1009",
    websiteUrl: "https://lonestargaragedoors.com",
    displayWebsite: "lonestargaragedoors.com",
    qrCodeUrl: "/q/lone-star-garage",
    qrLabel: "Scan to book",
    redemptionNote: "Bring in this card.",
    accentColor: "#77706A",
    iconType: "GD",
  }),
  createSlot({
    id: "template1-front-l4",
    side: "front",
    positionId: "F-L4",
    slotType: "frontStandard",
    category: "HVAC",
    businessName: "COMFORT AIR SOLUTIONS",
    description: "Family-owned HVAC care for tune-ups, repairs, and replacements that keep homes comfortable.",
    offer: "$75 OFF",
    offerSubtext: "Any completed repair",
    phone: "(210) 555-1004",
    websiteUrl: "https://comfortairtx.com",
    displayWebsite: "comfortairtx.com",
    qrCodeUrl: "/q/comfort-air",
    qrLabel: "Scan to book",
    redemptionNote: "Mention this card.",
    accentColor: "#0B2F4A",
    iconType: "AC",
  }),
  createSlot({
    id: "template1-front-l5",
    side: "front",
    positionId: "F-L5",
    slotType: "frontStandard",
    category: "PEST CONTROL",
    businessName: "SAFEGUARD PEST CONTROL",
    description: "Targeted protection for ants, roaches, rodents, termites, and seasonal household pests.",
    offer: "$25 OFF",
    offerSubtext: "Initial pest service",
    phone: "(210) 555-1006",
    websiteUrl: "https://safeguardpesttx.com",
    displayWebsite: "safeguardpesttx.com",
    qrCodeUrl: "/q/safeguard-pest",
    qrLabel: "Scan offer",
    redemptionNote: "Mention this card.",
    accentColor: "#D13F1F",
    iconType: "PC",
  }),
  createSlot({
    id: "template1-front-l6",
    side: "front",
    positionId: "F-L6",
    slotType: "frontStandard",
    category: "POOL SERVICE",
    businessName: "AQUA BLUE POOL CARE",
    description: "Weekly pool cleaning, equipment checks, chemical balancing, and dependable repairs.",
    offer: "$25 OFF",
    offerSubtext: "Your first month",
    phone: "(210) 555-1011",
    websiteUrl: "https://aquabluepoolcare.com",
    displayWebsite: "aquabluepoolcare.com",
    qrCodeUrl: "/q/aqua-blue-pools",
    qrLabel: "Scan to book",
    redemptionNote: "Mention this card.",
    accentColor: "#77706A",
    iconType: "PS",
  }),
  createSlot({
    id: "template1-front-r1",
    side: "front",
    positionId: "F-R1",
    slotType: "frontStandard",
    category: "ROOFING",
    businessName: "SUMMIT ROOFING",
    description: "Roof inspections, storm repairs, replacements, and honest guidance for Texas homeowners.",
    offer: "$100 OFF",
    offerSubtext: "A complete roof replacement",
    phone: "(210) 555-1002",
    websiteUrl: "https://summitroofingtx.com",
    displayWebsite: "summitroofingtx.com",
    qrCodeUrl: "/q/summit-roofing",
    qrLabel: "Scan details",
    redemptionNote: "Bring in this card.",
    accentColor: "#0B2F4A",
    iconType: "RF",
  }),
  createSlot({
    id: "template1-front-r2",
    side: "front",
    positionId: "F-R2",
    slotType: "frontStandard",
    category: "LANDSCAPING",
    businessName: "GREENSCAPE SOLUTIONS",
    description: "Landscape design, sod, cleanups, irrigation, and year-round curb appeal maintenance.",
    offer: "10% OFF",
    offerSubtext: "Your first landscape project",
    phone: "(210) 555-1003",
    websiteUrl: "https://greenscapetx.com",
    displayWebsite: "greenscapetx.com",
    qrCodeUrl: "/q/greenscape",
    qrLabel: "Scan to book",
    redemptionNote: "Mention this card.",
    accentColor: "#D13F1F",
    iconType: "LS",
  }),
  createSlot({
    id: "template1-front-r3",
    side: "front",
    positionId: "F-R3",
    slotType: "frontStandard",
    category: "CONCRETE",
    businessName: "CUSTOM CONCRETE CO.",
    description: "Driveways, patios, walkways, foundations, and decorative concrete built to last.",
    offer: "$100 OFF",
    offerSubtext: "Projects over $2,500",
    phone: "(210) 555-1007",
    websiteUrl: "https://customconcretetx.com",
    displayWebsite: "customconcretetx.com",
    qrCodeUrl: "/q/custom-concrete",
    qrLabel: "Scan estimate",
    redemptionNote: "Mention this card.",
    accentColor: "#77706A",
    iconType: "CC",
  }),
  createSlot({
    id: "template1-front-r4",
    side: "front",
    positionId: "F-R4",
    slotType: "frontStandard",
    category: "JUNK REMOVAL",
    businessName: "CLEAR OUT HAULING",
    description: "Friendly crews remove furniture, appliances, yard debris, and renovation clutter.",
    offer: "$25 OFF",
    offerSubtext: "Any full truck load",
    phone: "(210) 555-1008",
    websiteUrl: "https://clearouthauling.com",
    displayWebsite: "clearouthauling.com",
    qrCodeUrl: "/q/clear-out-hauling",
    qrLabel: "Scan to book",
    redemptionNote: "Mention this card.",
    accentColor: "#C9993E",
    iconType: "JR",
  }),
  createSlot({
    id: "template1-front-r5",
    side: "front",
    positionId: "F-R5",
    slotType: "frontStandard",
    category: "REMODELING",
    businessName: "BETTER BUILT REMODELING",
    description: "Thoughtful kitchen, bath, and whole-home remodeling with clear project communication.",
    offer: "$100 OFF",
    offerSubtext: "Projects over $5,000",
    phone: "(210) 555-1012",
    websiteUrl: "https://betterbuilttx.com",
    displayWebsite: "betterbuilttx.com",
    qrCodeUrl: "/q/better-built",
    qrLabel: "Scan portfolio",
    redemptionNote: "Bring in this card.",
    accentColor: "#0B2F4A",
    iconType: "RM",
  }),
  createSlot({
    id: "template1-front-r6",
    side: "front",
    positionId: "F-R6",
    slotType: "frontStandard",
    category: "TREE SERVICE",
    businessName: "TEXAS TREE CARE",
    description: "Professional trimming, hazardous tree removal, stump grinding, and storm cleanup.",
    offer: "$50 OFF",
    offerSubtext: "Any service over $500",
    phone: "(210) 555-1013",
    websiteUrl: "https://texastreecare.com",
    displayWebsite: "texastreecare.com",
    qrCodeUrl: "/q/texas-tree-care",
    qrLabel: "Scan estimate",
    redemptionNote: "Mention this card.",
    accentColor: "#D13F1F",
    iconType: "TC",
  }),
]

export const template1BackSlots: AdvertiserSlot[] = [
  createSlot({
    id: "template1-back-t1",
    side: "back",
    positionId: "B-T1",
    slotType: "backStandard",
    category: "WINDOWS",
    businessName: "CLIMATE PRO WINDOWS",
    description: "Energy-efficient replacement windows and doors installed for comfort, value, and curb appeal.",
    offer: "$100 OFF",
    offerSubtext: "Five or more windows",
    phone: "(210) 555-1010",
    websiteUrl: "https://climateprowindows.com",
    displayWebsite: "climateprowindows.com",
    qrCodeUrl: "/q/climate-pro-windows",
    qrLabel: "Scan estimate",
    redemptionNote: "Mention this card.",
    accentColor: "#0B2F4A",
    iconType: "WN",
  }),
  createSlot({
    id: "template1-back-t2",
    side: "back",
    positionId: "B-T2",
    slotType: "backStandard",
    category: "HANDYMAN",
    businessName: "FIX-IT ALL SERVICES",
    description: "Dependable help for repairs, installations, punch lists, and the projects around your home.",
    offer: "$15 OFF",
    offerSubtext: "Your first service hour",
    phone: "(210) 555-1014",
    websiteUrl: "https://fixitallconverse.com",
    displayWebsite: "fixitallconverse.com",
    qrCodeUrl: "/q/fix-it-all",
    qrLabel: "Scan to book",
    redemptionNote: "Mention this card.",
    accentColor: "#D13F1F",
    iconType: "HM",
  }),
  createSlot({
    id: "template1-back-t3",
    side: "back",
    positionId: "B-T3",
    slotType: "backStandard",
    category: "FENCING",
    businessName: "STRONGHOLD FENCING",
    description: "Wood, ornamental iron, privacy, and ranch fencing designed for long-lasting Texas properties.",
    offer: "$50 OFF",
    offerSubtext: "New fence installation",
    phone: "(210) 555-1015",
    websiteUrl: "https://strongholdfencingtx.com",
    displayWebsite: "strongholdfencingtx.com",
    qrCodeUrl: "/q/stronghold-fencing",
    qrLabel: "Scan estimate",
    redemptionNote: "Bring in this card.",
    accentColor: "#77706A",
    iconType: "FN",
  }),
  createSlot({
    id: "template1-back-t4",
    side: "back",
    positionId: "B-T4",
    slotType: "backStandard",
    category: "HOUSE CLEANING",
    businessName: "SPARKLE HOME CLEANING",
    description: "Recurring and deep home cleaning from a reliable local team that respects your space.",
    offer: "$50 OFF",
    offerSubtext: "Your first deep cleaning",
    phone: "(210) 555-1016",
    websiteUrl: "https://sparklecleantx.com",
    displayWebsite: "sparklecleantx.com",
    qrCodeUrl: "/q/sparkle-cleaning",
    qrLabel: "Scan to book",
    redemptionNote: "Mention this card.",
    accentColor: "#C9993E",
    iconType: "HC",
  }),
  createSlot({
    id: "template1-back-b1",
    side: "back",
    positionId: "B-B1",
    slotType: "backStandard",
    category: "PAINTING",
    businessName: "BRUSHSTROKE PAINTING",
    description: "Interior and exterior painting with careful preparation, clean lines, and respectful crews.",
    offer: "$100 OFF",
    offerSubtext: "Projects over $2,000",
    phone: "(210) 555-1017",
    websiteUrl: "https://brushstroketx.com",
    displayWebsite: "brushstroketx.com",
    qrCodeUrl: "/q/brushstroke-painting",
    qrLabel: "Scan estimate",
    redemptionNote: "Mention this card.",
    accentColor: "#D13F1F",
    iconType: "PT",
  }),
  createSlot({
    id: "template1-back-b2",
    side: "back",
    positionId: "B-B2",
    slotType: "backStandard",
    category: "WATER HEATERS",
    businessName: "HOT FLOW WATER HEATERS",
    description: "Tank and tankless water heater installation, maintenance, and prompt repair service.",
    offer: "$30 OFF",
    offerSubtext: "Any completed repair",
    phone: "(210) 555-1018",
    websiteUrl: "https://hotflowheaters.com",
    displayWebsite: "hotflowheaters.com",
    qrCodeUrl: "/q/hot-flow-heaters",
    qrLabel: "Scan to book",
    redemptionNote: "Mention this card.",
    accentColor: "#0B2F4A",
    iconType: "WH",
  }),
  createSlot({
    id: "template1-back-b3",
    side: "back",
    positionId: "B-B3",
    slotType: "backStandard",
    category: "GUTTERS",
    businessName: "CLEAN FLOW GUTTER CARE",
    description: "Gutter cleaning, repairs, guards, and drainage solutions that protect your foundation.",
    offer: "$25 OFF",
    offerSubtext: "Any complete gutter service",
    phone: "(210) 555-1019",
    websiteUrl: "https://cleanflowgutters.com",
    displayWebsite: "cleanflowgutters.com",
    qrCodeUrl: "/q/clean-flow-gutters",
    qrLabel: "Scan estimate",
    redemptionNote: "Bring in this card.",
    accentColor: "#77706A",
    iconType: "GT",
  }),
  createSlot({
    id: "template1-back-b4",
    side: "back",
    positionId: "B-B4",
    slotType: "backStandard",
    category: "PRESSURE WASHING",
    businessName: "TEXAS CLEAN EXTERIORS",
    description: "House washing, concrete cleaning, and soft-wash roof care for a brighter property.",
    offer: "10% OFF",
    offerSubtext: "Your first exterior cleaning",
    phone: "(210) 555-1020",
    websiteUrl: "https://texascleanexteriors.com",
    displayWebsite: "texascleanexteriors.com",
    qrCodeUrl: "/q/texas-clean-exteriors",
    qrLabel: "Scan to book",
    redemptionNote: "Mention this card.",
    accentColor: "#C9993E",
    iconType: "PW",
  }),
]

export const template1PremiumAdvertiser = createSlot({
  id: "template1-back-premium",
  side: "back",
  positionId: "B-PC",
  slotType: "premiumCenterBack",
  category: "PREMIUM HOME SERVICES",
  businessName: "HILL COUNTRY HOME PROS",
  description: "One trusted team for remodeling, repairs, and major home improvements from plan to finish.",
  offer: "$250 OFF",
  offerSubtext: "Projects over $7,500",
  phone: "(210) 555-2001",
  websiteUrl: "https://hillcountryhomepros.com",
  displayWebsite: "hillcountryhomepros.com",
  qrCodeUrl: "/q/hill-country-home-pros",
  qrLabel: "Scan portfolio",
  redemptionNote: "Mention this card.",
  accentColor: "#D13F1F",
  iconType: "HP",
})

export const TEMPLATE_1_DOUBLE_POSITIONS = {
  front: [
    ["F-L1", "F-L4"],
    ["F-L2", "F-L5"],
    ["F-L3", "F-L6"],
    ["F-R1", "F-R4"],
    ["F-R2", "F-R5"],
    ["F-R3", "F-R6"],
  ],
  back: [
    ["B-T1", "B-T2"],
    ["B-T3", "B-T4"],
    ["B-B1", "B-B2"],
    ["B-B3", "B-B4"],
  ],
} as const
